name: fenicsx-0.11
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - fenics-dolfinx=0.11.0
  - mpich
  - python-gmsh
  - matplotlib
  - nbclient
  - ipykernel
  - scipy
  - nbstripout
